[project]
name = "FLT"
namespace = "FLT"

[[modules]]
name = "FLT.Assumptions.KnownIn1980s"

[[modules]]
name = "FLT.Assumptions.Mazur"

[[modules]]
name = "FLT.Assumptions.Odlyzko"

[[modules]]
name = "FLT.AutomorphicForm.QuaternionAlgebra.Defs"

[[modules]]
name = "FLT.AutomorphicForm.QuaternionAlgebra.FiniteDimensional"

[[modules]]
name = "FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Abstract"

[[modules]]
name = "FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Concrete"

[[modules]]
name = "FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Local"

[[modules]]
name = "FLT.Basic.FreyPackage"

[[modules]]
name = "FLT.Basic.Reductions"

[[modules]]
name = "FLT.Data.Hurwitz"

[[modules]]
name = "FLT.Data.HurwitzRatHat"

[[modules]]
name = "FLT.Data.QHat"

[[modules]]
name = "FLT.DedekindDomain.AdicValuation"

[[modules]]
name = "FLT.DedekindDomain.Completion.BaseChange"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.BaseChange"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.IsDirectLimitRestricted"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.LocalUnits"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.TensorPi"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.TensorProduct"

[[modules]]
name = "FLT.DedekindDomain.FiniteAdeleRing.TensorRestrictedProduct"

[[modules]]
name = "FLT.DedekindDomain.IntegralClosure"

[[modules]]
name = "FLT.Deformations.Algebra.InverseLimit.Basic"

[[modules]]
name = "FLT.Deformations.Algebra.InverseLimit.Topology"

[[modules]]
name = "FLT.Deformations.Categories"

[[modules]]
name = "FLT.Deformations.ContinuousRepresentation.IsTopologicalModule"

[[modules]]
name = "FLT.Deformations.IsProartinian"

[[modules]]
name = "FLT.Deformations.IsResidueAlgebra"

[[modules]]
name = "FLT.Deformations.Lemmas"

[[modules]]
name = "FLT.Deformations.LiftFunctor"

[[modules]]
name = "FLT.Deformations.Representable"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.AbsoluteGaloisGroup"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.ContinuousSMulDiscrete"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.Etale"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.Frobenius"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.GaloisRep"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.GaloisRepFamily"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.IntegralClosure"

[[modules]]
name = "FLT.Deformations.RepresentationTheory.Irreducible"

[[modules]]
name = "FLT.Deformations.Subfunctor"

[[modules]]
name = "FLT.DivisionAlgebra.Finiteness"

[[modules]]
name = "FLT.EllipticCurve.Torsion"

[[modules]]
name = "FLT.GaloisRepresentation.Automorphic"

[[modules]]
name = "FLT.GaloisRepresentation.Cyclotomic"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.Defs"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.Family"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.Frey"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.Lift"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.ModThree"

[[modules]]
name = "FLT.GaloisRepresentation.HardlyRamified.Threeadic"

[[modules]]
name = "FLT.GlobalLanglandsConjectures.GLnDefs"

[[modules]]
name = "FLT.GlobalLanglandsConjectures.GLzero"

[[modules]]
name = "FLT.GroupScheme.FiniteFlat"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.AddEquiv"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.AdeleRing"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.FiniteAdeleRing"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.FiniteDimensional"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.Padic"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.RealComplex"

[[modules]]
name = "FLT.HaarMeasure.HaarChar.Ring"

[[modules]]
name = "FLT.HaarMeasure.MeasurableSpacePadics"

[[modules]]
name = "FLT.Hacks.RightActionInstances"

[[modules]]
name = "FLT.Mathlib.Algebra.Algebra.Bilinear"

[[modules]]
name = "FLT.Mathlib.Algebra.Algebra.Hom"

[[modules]]
name = "FLT.Mathlib.Algebra.Algebra.Pi"

[[modules]]
name = "FLT.Mathlib.Algebra.Algebra.Tower"

[[modules]]
name = "FLT.Mathlib.Algebra.Central.TensorProduct"

[[modules]]
name = "FLT.Mathlib.Algebra.FixedPoints.Basic"

[[modules]]
name = "FLT.Mathlib.Algebra.IsDirectLimit"

[[modules]]
name = "FLT.Mathlib.Algebra.IsQuaternionAlgebra"

[[modules]]
name = "FLT.Mathlib.Algebra.Module.Submodule.Basic"

[[modules]]
name = "FLT.Mathlib.Algebra.Order.AbsoluteValue.Basic"

[[modules]]
name = "FLT.Mathlib.Analysis.Normed.Ring.WithAbs"

[[modules]]
name = "FLT.Mathlib.Data.Fin.Basic"

[[modules]]
name = "FLT.Mathlib.Data.Real.Archimedean"

[[modules]]
name = "FLT.Mathlib.Data.Set.Countable"

[[modules]]
name = "FLT.Mathlib.Data.Set.Prod"

[[modules]]
name = "FLT.Mathlib.GroupTheory.DoubleCoset"

[[modules]]
name = "FLT.Mathlib.GroupTheory.Index"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Countable"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Determinant"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Dimension.Constructions"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Matrix.Transvection"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.Pi"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.TensorProduct.Algebra"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.TensorProduct.Basis"

[[modules]]
name = "FLT.Mathlib.LinearAlgebra.TensorProduct.FiniteFree"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.AdeleRing"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.AdicCompletion"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.FiniteAdeleRing"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.InfinitePlace"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.Padic"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.RestrictedProduct"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Group.Action"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Group.Measure"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Haar.Extension"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Measure.Regular"

[[modules]]
name = "FLT.Mathlib.MeasureTheory.Measure.Typeclasses.Finite"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.AdeleRing"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.Completion"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.FiniteAdeleRing"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.InfiniteAdeleRing"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.InfinitePlace.Basic"

[[modules]]
name = "FLT.Mathlib.NumberTheory.NumberField.InfinitePlace.Completion"

[[modules]]
name = "FLT.Mathlib.NumberTheory.Padics.HeightOneSpectrum"

[[modules]]
name = "FLT.Mathlib.NumberTheory.Padics.PadicIntegers"

[[modules]]
name = "FLT.Mathlib.Order.Filter.Cofinite"

[[modules]]
name = "FLT.Mathlib.RepresentationTheory.Basic"

[[modules]]
name = "FLT.Mathlib.RingTheory.DedekindDomain.AdicValuation"

[[modules]]
name = "FLT.Mathlib.RingTheory.DedekindDomain.FiniteAdeleRing"

[[modules]]
name = "FLT.Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas"

[[modules]]
name = "FLT.Mathlib.RingTheory.Ideal.Quotient.Basic"

[[modules]]
name = "FLT.Mathlib.RingTheory.Localization.BaseChange"

[[modules]]
name = "FLT.Mathlib.RingTheory.LocalRing.Defs"

[[modules]]
name = "FLT.Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic"

[[modules]]
name = "FLT.Mathlib.RingTheory.SimpleRing.TensorProduct"

[[modules]]
name = "FLT.Mathlib.RingTheory.TensorProduct.Basis"

[[modules]]
name = "FLT.Mathlib.RingTheory.TensorProduct.Pi"

[[modules]]
name = "FLT.Mathlib.RingTheory.Valuation.ValuationSubring"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Algebra.Hom"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.ContinuousMonoidHom"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Group.Quotient"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Group.Units"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Module.Equiv"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Module.FiniteDimension"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Module.ModuleTopology"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Module.Quotient"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Module.TensorProduct"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Monoid"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.MulAction"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Order.Field"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.RestrictedProduct.Basic"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.RestrictedProduct.Equiv"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.RestrictedProduct.Module"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.RestrictedProduct.TopologicalSpace"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.UniformRing"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Valued.ValuationTopology"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Valued.WithVal"

[[modules]]
name = "FLT.Mathlib.Topology.Algebra.Valued.WithZeroMulInt"

[[modules]]
name = "FLT.Mathlib.Topology.Bases"

[[modules]]
name = "FLT.Mathlib.Topology.Constructions"

[[modules]]
name = "FLT.Mathlib.Topology.HomToDiscrete"

[[modules]]
name = "FLT.Mathlib.Topology.Instances.Matrix"

[[modules]]
name = "FLT.Mathlib.Topology.MetricSpace.ProperSpace.InfinitePlace"

[[modules]]
name = "FLT.Mathlib.Topology.MetricSpace.Pseudo.Matrix"

[[modules]]
name = "FLT.Mathlib.Topology.Polish"

[[modules]]
name = "FLT.NumberField.AdeleRing"

[[modules]]
name = "FLT.NumberField.Completion.Finite"

[[modules]]
name = "FLT.NumberField.Completion.Infinite"

[[modules]]
name = "FLT.NumberField.DiscriminantBounds"

[[modules]]
name = "FLT.NumberField.HeightOneSpectrum"

[[modules]]
name = "FLT.NumberField.InfiniteAdeleRing"

[[modules]]
name = "FLT.NumberField.InfinitePlace.Dimension"

[[modules]]
name = "FLT.NumberField.InfinitePlace.Extension"

[[modules]]
name = "FLT.NumberField.InfinitePlace.WeakApproximation"

[[modules]]
name = "FLT.NumberField.Padics.RestrictedProduct"

[[modules]]
name = "FLT.Patching.Algebra"

[[modules]]
name = "FLT.Patching.Module"

[[modules]]
name = "FLT.Patching.Over"

[[modules]]
name = "FLT.Patching.REqualsT"

[[modules]]
name = "FLT.Patching.System"

[[modules]]
name = "FLT.Patching.Ultraproduct"

[[modules]]
name = "FLT.Patching.Utils.AdicTopology"

[[modules]]
name = "FLT.Patching.Utils.Depth"

[[modules]]
name = "FLT.Patching.Utils.InverseLimit"

[[modules]]
name = "FLT.Patching.Utils.Lemmas"

[[modules]]
name = "FLT.Patching.Utils.StructureFiniteness"

[[modules]]
name = "FLT.Patching.Utils.TopologicallyFG"

[[modules]]
name = "FLT.Patching.VanishingFilter"

[[modules]]
name = "FLT.QuaternionAlgebra.NumberField"

[[modules]]
name = "FLT.TateCurve.TateCurve"

[atlas]
root = "../lean-atlas-for-PrimeNumberTheoremAnd"
